# Generated by Django 3.1.7 on 2021-05-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
