# Generated by Django 3.1.7 on 2021-04-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceandpackagesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='priceandpackagesmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('quantity_purchased', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='priceandpackagespage',
        ),
    ]
