# Generated by Django 3.1.7 on 2021-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0003_privacypolicypage_termsncpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitemappage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sitemap/images/')),
            ],
        ),
    ]
