# Generated by Django 3.1.7 on 2021-05-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0004_sitemappage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
