# Generated by Django 3.1.7 on 2021-05-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0005_homepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicypage',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='sitemappage',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='termsncpage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
