# Generated by Django 3.2.4 on 2021-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0009_auto_20210724_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpage',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationpage',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
