# Generated by Django 3.2.4 on 2021-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0010_auto_20210726_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpage',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='consultationpage',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
