# Generated by Django 3.2.4 on 2021-07-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0017_ourteampage'),
    ]

    operations = [
        migrations.CreateModel(
            name='priceandpackagesmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('quantity_purchased', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
