# Generated by Django 3.2.4 on 2021-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0018_priceandpackagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceandpackagesmodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
