# Generated by Django 3.2.4 on 2021-07-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizlerapp', '0019_alter_priceandpackagesmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
