# Generated by Django 3.1.7 on 2021-04-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=True, upload_to='blog/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='long_description',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
