# Generated by Django 3.1.7 on 2021-04-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210423_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
