# Generated by Django 3.1.7 on 2021-05-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpageapp', '0002_auto_20210423_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpagepage',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
