# Generated by Django 3.1.7 on 2021-04-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
        ('consultationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationpage',
            name='service',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='servicesapp.servicespage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationpage',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
